name: Release Package

on:
  push:
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Artifacts
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            arch: amd64
            with_source: true
            build_firmware: true
          - runner: ubuntu-24.04-arm
            arch: arm64
            with_source: false
            build_firmware: false
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build SDK package
        uses: docker/build-push-action@v6
        with:
          context: . # Use workspace context to keep .git
          file: Dockerfile.build_sdk
          build-args: |
            WITH_SOURCE=${{ matrix.with_source }}
          outputs: type=local,dest=build/
          cache-from: type=gha,scope=docker-build-${{ matrix.arch }}

      - name: Build firmware package
        if: matrix.build_firmware
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.build_firmware
          outputs: type=local,dest=build/
          cache-from: type=gha,scope=docker-build-${{ matrix.arch }}

      - name: Upload SDK source
        if: matrix.with_source
        uses: actions/upload-artifact@v6
        with:
          name: librmcs-sdk-src
          path: build/librmcs-sdk-src*
          if-no-files-found: error

      - name: Upload SDK Debian package
        uses: actions/upload-artifact@v6
        with:
          name: librmcs-sdk-deb-${{ matrix.arch }}
          path: build/librmcs-sdk*.deb
          if-no-files-found: error

      - name: Upload firmware
        if: matrix.build_firmware
        uses: actions/upload-artifact@v6
        with:
          name: librmcs-firmware
          path: build/librmcs-firmware*
          if-no-files-found: error

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts
          pattern: librmcs-*
          merge-multiple: true

      - name: Create Pre-Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/*
          prerelease: true
          generate_release_notes: true
